---
language: elixir
elixir:
  - 1.8.1
  - 1.7
  - 1.6
  - 1.5
  - 1.4
otp_release:
  - 21.0
  - 20.3
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.5
      otp_release: 20.3
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.6.6
      otp_release: 18.3
    - elixir: 1.8.1
      otp_release: 19.3
    - elixir: 1.8.1
      otp_release: 18.3

script:
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.8.1" ]; then mix format --check-formatted --dry-run; fi
  - MIX_ENV=test mix compile && mix test
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.8.1" ] && [ "$TRAVIS_OTP_RELEASE" = "21.0" ]; then mix dialyzer; fi

cache:
  directories:
    - .mix
    - _build
